all:
	@as exercicio2.s --gstabs -o exercicio2.o
	@gcc exercicio2.o -no-pie -o exercicio2
	@as exercicio3.s --gstabs -o exercicio3.o
	@gcc exercicio3.o -no-pie -o exercicio3
clear:
	@rm exercicio2.o exercicio2 exercicio3.o exercicio3
